image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

nginxConfig:
    serverName: "myapp.local"

postgresImage:
    repository: postgres
    tag: 13
    pullPolicy: IfNotPresent

service:
    name: my-service
    type: ClusterIP
    port: 80

postgresService:
    name: postgres-service
    type: ClusterIP
    port: 5432

persistence:
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClassName: manual
    reclaimPolicy: Retain

secret:
    username: admin
    password: password123
    database: mydatabase

job:
    image: alpine
    tag: latest
    imagePullPolicy: IfNotPresent
    backoffLimit: 4

customResource:
    enabled: true
    name: my-custom-resource

# Optional overrides for names, useful for Helm templates
nameOverride: ""
fullnameOverride: ""
