# Functional PV

apiVersion: v1
kind: PersistentVolume
metadata:
    name: faulty-pv-1
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: manual
    hostPath:
        path: "/mnt/data"
    claimRef:
        namespace: coaching
        name: faulty-pvc-1
