apiVersion: apps/v1
kind: Deployment
metadata:
    name: external-secrets-controller
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "1"
        "helm.sh/hook-delete-policy": before-hook-creation
spec:
    replicas: 1
    selector:
        matchLabels:
            app: external-secrets-controller
    template:
        metadata:
            labels:
                app: external-secrets-controller
        spec:
            containers:
                -   name: external-secrets-controller
                    image: external-secrets/kubernetes-external-secrets:latest
                    ports:
                        -   containerPort: 80
                    env:
                        -   name: VAULT_ADDR
                            value: "http://172.18.249.95:8200"
---
apiVersion: v1
kind: Service
metadata:
    name: external-secrets-controller
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "1"
        "helm.sh/hook-delete-policy": before-hook-creation
spec:
    ports:
        - port: 80
    selector:
        app: external-secrets-controller
