apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: customresources.example.com
spec:
    group: example.com
    versions:
        - name: v1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              foo:
                                  type: string
    scope: Namespaced
    names:
        plural: customresources
        singular: customresource
        kind: CustomResource
        shortNames:
            - cr
