apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: externalsecrets.external-secrets.io
spec:
    group: external-secrets.io
    versions:
        - name: v1beta1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      apiVersion:
                          type: string
                      kind:
                          type: string
                      metadata:
                          type: object
                      spec:
                          type: object
                          properties:
                              backendType:
                                  type: string
                              provider:
                                  type: object
                                  properties:
                                      vault:
                                          type: object
                                          properties:
                                              server:
                                                  type: string
                                              path:
                                                  type: string
                                              version:
                                                  type: string
                                              auth:
                                                  type: object
                                                  properties:
                                                      tokenSecretRef:
                                                          type: object
                                                          properties:
                                                              name:
                                                                  type: string
                                                              key:
                                                                  type: string
                              data:
                                  type: array
                                  items:
                                      type: object
                                      properties:
                                          key:
                                              type: string
                                          name:
                                              type: string
                                          property:
                                              type: string
    scope: Namespaced
    names:
        plural: externalsecrets
        singular: externalsecret
        kind: ExternalSecret
