apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "my-helm-chart.fullname" . }}-configmap
data:
    nginx.conf: |
        user  nginx;
        worker_processes  auto;

        events {
            worker_connections 1024;
        }

        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;

            # Die Konfigurationsdateien mit den Server-Blöcken einbinden
            include /etc/nginx/conf.d/*.conf;
        }

    default.conf: |
        server {
          listen 80;
          server_name {{ .Values.nginxConfig.serverName }};
        
          location / {
            root /usr/share/nginx/html;
            index index.html;
          }
        }
    additional_setting: "true"
