apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "my-helm-chart.fullname" . }}-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ include "my-helm-chart.name" . }}
    template:
        metadata:
            labels:
                app: {{ include "my-helm-chart.name" . }}
        spec:
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: config-volume
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
                  env:
                      - name: ADDITIONAL_SETTING
                        valueFrom:
                            configMapKeyRef:
                                name: {{ include "my-helm-chart.fullname" . }}-configmap
                                key: additional_setting
                  resources:
                      limits:
                          cpu: "500m"
                          memory: "256Mi"
                      requests:
                          cpu: "250m"
                          memory: "128Mi"
            volumes:
                - name: config-volume
                  configMap:
                      name: {{ include "my-helm-chart.fullname" . }}-configmap
