apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "my-helm-chart.fullname" . }}-deployment
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ include "my-helm-chart.name" . }}
    template:
        metadata:
            labels:
                app: {{ include "my-helm-chart.name" . }}
        spec:
            containers:
                - name: {{ .Chart.Name }}
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  ports:
                      - containerPort: 80
                  resources:
                      limits:
                          cpu: "500m"
                          memory: "256Mi"
                      requests:
                          cpu: "250m"
                          memory: "128Mi"
