apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: helm-chart-external-secret
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": before-hook-creation
spec:
    backendType: vault
    provider:
        vault:
            server: "http://host.docker.internal:8200"  # Zugriff auf Vault von Kubernetes aus - läuft via Docker Compose
            path: "secret/data/myapp"  # Pfad zum Secret in Vault
            version: "v2"
            auth:
                tokenSecretRef:
                    name: vault-token
                    key: token
    data:
        - key: credentials
          name: username
          property: username
        - key: credentials
          name: password
          property: password
        - key: database
          name: database
          property: database
