apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ include "my-helm-chart.fullname" . }}-pv
spec:
    capacity:
        storage: {{ .Values.persistence.size }}
    accessModes:
        - {{ .Values.persistence.accessMode }}
    storageClassName: {{ .Values.persistence.storageClassName }}
    hostPath:
        path: "/mnt/data"
