apiVersion: v1
kind: Service
metadata:
    name: {{ include "my-helm-chart.fullname" . }}-service-postgres
spec:
    type: {{ .Values.postgresService.type }}
    ports:
        - port: {{ .Values.postgresService.port }}
    selector:
        app: postgres
