apiVersion: v1
kind: Secret
metadata:
    name: helm-chart-secret
type: Opaque
data:
    username: {{ .Values.secret.username | b64enc | quote }}
    password: {{ .Values.secret.password | b64enc | quote }}
    database: {{ .Values.secret.database | b64enc | quote }}
