apiVersion: v1
kind: Secret
metadata:
    name: helm-chart-secret
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
    username: {{ .Values.secret.username | b64enc | quote }}
    password: {{ .Values.secret.password | b64enc | quote }}
    database: {{ .Values.secret.database | b64enc | quote }}
