apiVersion: v1
kind: Service
metadata:
    name: unique-service-name
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
    selector:
        app: {{ include "my-helm-chart.name" . }}
