apiVersion: v1
kind: Secret
metadata:
    name: vault-token
    annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
    token: cm9vdA==
