name: Verify structure for HELM Chart

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  helm-lint:
    name: Lint HELM Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Lint Helm Chart
        run: helm lint .

      - name: Validate Helm Templates
        run: helm template . --dry-run
